version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: color-name-list
    versions:
    - 7.32.0
    - 7.33.0
    - 7.33.1
    - 7.34.0
    - 7.35.0
    - 7.36.0
    - 7.37.0
    - 7.38.0
    - 7.39.0
    - 7.40.0
    - 7.41.0
    - 7.42.0
    - 7.43.0
    - 7.44.0
    - 7.45.1
    - 8.0.0
    - 8.4.0
    - 8.5.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: standard-version
    versions:
    - 9.1.1
